// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace be.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250620065529_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("be.Models.Account", b =>
                {
                    b.Property<string>("AccountID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LockUntil")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LoginAttempt")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AccountID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("unique_email");

                    b.HasIndex("Phone")
                        .HasDatabaseName("index_phone");

                    b.HasIndex("UserName")
                        .HasDatabaseName("index_username");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("be.Models.AllCodes", b =>
                {
                    b.Property<int>("CodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodeID"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodeValueVI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ExtraValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CodeID");

                    b.HasIndex("Type")
                        .HasDatabaseName("index_type");

                    b.HasIndex("Type", "Code")
                        .IsUnique()
                        .HasDatabaseName("unique_type_code");

                    b.ToTable("AllCodes");
                });

            modelBuilder.Entity("be.Models.Banner", b =>
                {
                    b.Property<int>("BannerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BannerID"));

                    b.Property<string>("BannerImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BannerStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HiddenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BannerID");

                    b.HasIndex("ProductID")
                        .HasDatabaseName("index_product_id");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("be.Models.BlacklistToken", b =>
                {
                    b.Property<int>("TokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtraValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TokenID");

                    b.HasIndex("Token")
                        .HasDatabaseName("index_token");

                    b.ToTable("BlacklistTokens");
                });

            modelBuilder.Entity("be.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemID"));

                    b.Property<string>("AccountID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountID1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ItemPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ItemQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ProductDetailID")
                        .HasColumnType("int");

                    b.Property<int?>("ProductDetailID1")
                        .HasColumnType("int");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductID1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CartItemID");

                    b.HasIndex("AccountID")
                        .HasDatabaseName("index_account_id");

                    b.HasIndex("AccountID1");

                    b.HasIndex("ProductDetailID")
                        .HasDatabaseName("index_product_detail_id");

                    b.HasIndex("ProductDetailID1");

                    b.HasIndex("ProductID")
                        .HasDatabaseName("index_product_id");

                    b.HasIndex("ProductID1");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("be.Models.Coupon", b =>
                {
                    b.Property<int>("CouponID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponID"));

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CouponDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CouponStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaxDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinOrderValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CouponID");

                    b.HasIndex("CouponCode")
                        .IsUnique()
                        .HasDatabaseName("unique_coupon_code");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("index_date_range");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("be.Models.Image", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ImageID");

                    b.HasIndex("ReferenceID");

                    b.HasIndex("ReferenceType", "ReferenceID")
                        .HasDatabaseName("index_reference");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("be.Models.Invoice", b =>
                {
                    b.Property<string>("InvoiceID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CancelReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CouponID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.HasKey("InvoiceID");

                    b.HasIndex("AccountID")
                        .HasDatabaseName("index_account_id");

                    b.HasIndex("CouponID")
                        .HasDatabaseName("index_coupon_id");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("be.Models.InvoiceDetail", b =>
                {
                    b.Property<int>("InvoiceDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceDetailID"));

                    b.Property<string>("InvoiceID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InvoiceID1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ItemPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ItemQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ProductDetailID")
                        .HasColumnType("int");

                    b.Property<int?>("ProductDetailID1")
                        .HasColumnType("int");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductID1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("InvoiceDetailID");

                    b.HasIndex("InvoiceID")
                        .HasDatabaseName("index_invoice_id");

                    b.HasIndex("InvoiceID1");

                    b.HasIndex("ProductDetailID")
                        .HasDatabaseName("index_product_detail_id");

                    b.HasIndex("ProductDetailID1");

                    b.HasIndex("ProductID")
                        .HasDatabaseName("index_product_id");

                    b.HasIndex("ProductID1");

                    b.ToTable("InvoiceDetails");
                });

            modelBuilder.Entity("be.Models.Product", b =>
                {
                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductID");

                    b.HasIndex("ProductName")
                        .HasDatabaseName("index_product_name");

                    b.HasIndex("ProductType")
                        .HasDatabaseName("index_product_type");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("be.Models.ProductDetail", b =>
                {
                    b.Property<int>("ProductDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductDetailID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetailStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ExtraPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Promotion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoldCount")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductDetailID");

                    b.HasIndex("ProductID")
                        .HasDatabaseName("index_product_id");

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("be.Models.ProductPetType", b =>
                {
                    b.Property<int>("ProductPetTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductPetTypeID"));

                    b.Property<string>("PetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductPetTypeID");

                    b.HasIndex("ProductID")
                        .HasDatabaseName("index_product_id");

                    b.ToTable("ProductPetTypes");
                });

            modelBuilder.Entity("be.Models.Banner", b =>
                {
                    b.HasOne("be.Models.Product", "Product")
                        .WithMany("Banners")
                        .HasForeignKey("ProductID");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("be.Models.CartItem", b =>
                {
                    b.HasOne("be.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_Accounts_AccountID");

                    b.HasOne("be.Models.Account", null)
                        .WithMany("CartItems")
                        .HasForeignKey("AccountID1");

                    b.HasOne("be.Models.ProductDetail", "ProductDetail")
                        .WithMany()
                        .HasForeignKey("ProductDetailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_ProductDetails_ProductDetailID");

                    b.HasOne("be.Models.ProductDetail", null)
                        .WithMany("CartItems")
                        .HasForeignKey("ProductDetailID1");

                    b.HasOne("be.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_Products_ProductID");

                    b.HasOne("be.Models.Product", null)
                        .WithMany("CartItems")
                        .HasForeignKey("ProductID1");

                    b.Navigation("Account");

                    b.Navigation("Product");

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("be.Models.Image", b =>
                {
                    b.HasOne("be.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ReferenceID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Image_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("be.Models.Invoice", b =>
                {
                    b.HasOne("be.Models.Account", "Account")
                        .WithMany("Invoices")
                        .HasForeignKey("AccountID");

                    b.HasOne("be.Models.Coupon", "Coupon")
                        .WithMany("Invoices")
                        .HasForeignKey("CouponID");

                    b.Navigation("Account");

                    b.Navigation("Coupon");
                });

            modelBuilder.Entity("be.Models.InvoiceDetail", b =>
                {
                    b.HasOne("be.Models.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceDetails_Invoices_InvoiceID");

                    b.HasOne("be.Models.Invoice", null)
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceID1");

                    b.HasOne("be.Models.ProductDetail", "ProductDetail")
                        .WithMany()
                        .HasForeignKey("ProductDetailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceDetails_ProductDetails_ProductDetailID");

                    b.HasOne("be.Models.ProductDetail", null)
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("ProductDetailID1");

                    b.HasOne("be.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceDetails_Products_ProductID");

                    b.HasOne("be.Models.Product", null)
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("ProductID1");

                    b.Navigation("Invoice");

                    b.Navigation("Product");

                    b.Navigation("ProductDetail");
                });

            modelBuilder.Entity("be.Models.ProductDetail", b =>
                {
                    b.HasOne("be.Models.Product", "Product")
                        .WithMany("ProductDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("be.Models.ProductPetType", b =>
                {
                    b.HasOne("be.Models.Product", "Product")
                        .WithMany("ProductPetTypes")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("be.Models.Account", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("be.Models.Coupon", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("be.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("be.Models.Product", b =>
                {
                    b.Navigation("Banners");

                    b.Navigation("CartItems");

                    b.Navigation("Images");

                    b.Navigation("InvoiceDetails");

                    b.Navigation("ProductDetails");

                    b.Navigation("ProductPetTypes");
                });

            modelBuilder.Entity("be.Models.ProductDetail", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("InvoiceDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
